<?php
/**
 * FindListingRecommendationRequestTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  eBay\Sell\Recommendation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Recommendation API
 *
 * The <b>Recommendation API</b> returns information that sellers can use to optimize the configuration of their listings on eBay. <br><br>Currently, the API contains a single method, <b>findListingRecommendations</b>. This method provides information that sellers can use to configure Promoted Listings ad campaigns to maximize the visibility of their items in the eBay marketplace.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Recommendation\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FindListingRecommendationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description An list of listing ID values for which you want Promoted Listings ad configuration information.
 * @package     eBay\Sell\Recommendation
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FindListingRecommendationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FindListingRecommendationRequest"
     */
    public function testFindListingRecommendationRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "listing_ids"
     */
    public function testPropertyListingIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
